### ISSUE TITLE
Add PHP FPM monitoring

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-nginx#1]
Maybe needs to be implemented at spm-agent level if it's the same for Nginx and Apache
Some potentially useful pointers:
https://www.npmjs.com/package/pm2-php-fpm
https://support.serverdensity.com/hc/en-us/articles/212603057-Monitoring-PHP-FPM
https://www.datadoghq.com/blog/track-your-php-fpm-performance-with-datadog/
https://scoutapp.com/plugin_urls/471-php-fpm-status

**Comment by megastef** [comment]
Solved with https://github.com/sematext/sematext-agent-nginx/commit/5f2612b488ae50e04550b18e204bcb475879317a

Documentation: https://github.com/sematext/sematext-agent-nginx/blob/master/php-fpm.md
